name: Hello-World NodeJS App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Change to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build # Replace with your actual build command

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: your-application-name
          environment_name: your-environment-name
          version_label: ${{ github.sha }}
          region: us-east-1 # Change to your AWS region
          deployment_package: ./build/your-deployment-package.zip # Path to your build artifact
